<?php


namespace EasySwoole\Memcache\Tests;


use EasySwoole\Memcache\Config;
use EasySwoole\Memcache\Memcache;
use PHPUnit\Framework\TestCase;

class GetSetTest extends TestCase
{
    /** @var Memcache */
    private $client;

    function runTest()
    {
        $config = new Config([
            'host'=>MEMCACHE_HOST,
            'port'=>MEMCACHE_PORT
        ]);
        $this->client = new Memcache($config);
        return parent::runTest(); // TODO: Change the autogenerated stub
    }

    function testSet()
    {
        $this->assertEquals(true,$this->client->set('setStr','setStr'));
        $this->assertEquals(true,$this->client->set('setInt',1));
        $this->assertEquals(true,$this->client->set('keyNULL',NULL));
    }

    function testGet()
    {
        $this->assertEquals('setStr',$this->client->get('setStr'));
        $this->assertEquals(1,$this->client->get('setInt'));
        $this->assertEquals(null,$this->client->get('keyNULL'));
    }
}